[project]
name = "cplt-ds-instruksjoner"
version = "0.1.0"
description = "Workshop for å lage instruksjonsfiler til cplt for DS-er"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.5.2",
    "plotly>=6.9.0",
    "jupyter>=1.1.1",
    "google-cloud-bigquery>=3.44.0",
    "pandas>=3.0.5",
    "db-dtypes>=1.7.1",
]
